/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
	nodes: {
		Sphere: THREE.Mesh
		Sphere_1: THREE.Mesh
	}
	materials: {
		['Material.001']: THREE.MeshStandardMaterial
		Material: THREE.MeshPhysicalMaterial
	}
}

export function Globe() {
	const { nodes, materials } = useGLTF('/models/globe/globe.glb') as GLTFResult
	return (
		<group
			position={[0.261, 1, 0.368]}
			rotation={[-Math.PI / 2, 1.134, Math.PI / 2]}
			scale={3}
		>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Sphere.geometry}
				material={materials['Material.001']}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Sphere_1.geometry}
				material={materials.Material}
			/>
		</group>
	)
}

useGLTF.preload('/models/globe/globe.glb')
